## Libs

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns # For potentially nicer visualizations

# Set a consistent style for plots
plt.style.use('seaborn-v0_8-whitegrid')
print(f"PyTorch Version: {torch.__version__}")
print(f"NumPy Version: {np.__version__}")

PyTorch Version: 2.6.0+cu124
NumPy Version: 2.0.2


In [2]:
# --- PyTorch ---
pt_scalar = torch.tensor(5.0)
pt_vector = torch.tensor([1, 2, 3, 4])
pt_matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])
pt_3d_tensor = torch.randn(2, 3, 4) # Batch=2, Channels/Height=3, Width=4 (common for images)
pt_4d_tensor = torch.rand(10, 3, 32, 32) # Batch=10, Channels=3, Height=32, Width=32 (e.g., mini-batch of RGB images)

In [3]:
# --- NumPy ---
np_scalar = np.array(5.0)
np_vector = np.array([1, 2, 3, 4])
np_matrix = np.array([[1, 2], [3, 4], [5, 6]])
np_3d_array = np.random.randn(2, 3, 4)
np_4d_array = np.random.rand(10, 3, 32, 32)

In [4]:
print("--- PyTorch Examples ---")
print(f"Scalar: {pt_scalar}")
print(f"Vector: {pt_vector}")
print(f"Matrix:\n{pt_matrix}")
print(f"3D Tensor (sample element): {pt_3d_tensor[0,0,0]}") # Just to show it's populated
print(f"4D Tensor (sample element): {pt_4d_tensor[0,0,0,0]}")

print("\n--- NumPy Examples ---")
print(f"Scalar: {np_scalar}")
print(f"Vector: {np_vector}")
print(f"Matrix:\n{np_matrix}")
print(f"3D Array (sample element): {np_3d_array[0,0,0]}")
print(f"4D Array (sample element): {np_4d_array[0,0,0,0]}")

--- PyTorch Examples ---
Scalar: 5.0
Vector: tensor([1, 2, 3, 4])
Matrix:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
3D Tensor (sample element): -0.3703157305717468
4D Tensor (sample element): 0.34173113107681274

--- NumPy Examples ---
Scalar: 5.0
Vector: [1 2 3 4]
Matrix:
[[1 2]
 [3 4]
 [5 6]]
3D Array (sample element): -1.2411246493987331
4D Array (sample element): 0.8087239870305448


### Dimensions

In [5]:
print("--- PyTorch Shapes ---")
print(f"pt_scalar shape: {pt_scalar.shape}") # torch.Size([])
print(f"pt_vector shape: {pt_vector.shape}") # torch.Size([4])
print(f"pt_matrix shape: {pt_matrix.shape}") # torch.Size([3, 2])
print(f"pt_3d_tensor shape: {pt_3d_tensor.shape}") # torch.Size([2, 3, 4])
print(f"pt_4d_tensor shape: {pt_4d_tensor.shape}") # torch.Size([10, 3, 32, 32])

print("\n--- NumPy Shapes ---")
print(f"np_scalar shape: {np_scalar.shape}") # ()
print(f"np_vector shape: {np_vector.shape}") # (4,)
print(f"np_matrix shape: {np_matrix.shape}") # (3, 2)
print(f"np_3d_array shape: {np_3d_array.shape}") # (2, 3, 4)
print(f"np_4d_array shape: {np_4d_array.shape}") # (10, 3, 32, 32)

# Accessing individual dimension sizes
print(f"\nHeight of pt_matrix (dim 0): {pt_matrix.shape[0]}")
print(f"Width of pt_matrix (dim 1): {pt_matrix.shape[1]}")

--- PyTorch Shapes ---
pt_scalar shape: torch.Size([])
pt_vector shape: torch.Size([4])
pt_matrix shape: torch.Size([3, 2])
pt_3d_tensor shape: torch.Size([2, 3, 4])
pt_4d_tensor shape: torch.Size([10, 3, 32, 32])

--- NumPy Shapes ---
np_scalar shape: ()
np_vector shape: (4,)
np_matrix shape: (3, 2)
np_3d_array shape: (2, 3, 4)
np_4d_array shape: (10, 3, 32, 32)

Height of pt_matrix (dim 0): 3
Width of pt_matrix (dim 1): 2


#### Number of Dimensions (`.ndim` / `.dim()`)

In [6]:
print("--- PyTorch Number of Dimensions ---")
print(f"pt_scalar ndim: {pt_scalar.dim()}") # 0
print(f"pt_vector ndim: {pt_vector.dim()}") # 1
print(f"pt_matrix ndim: {pt_matrix.dim()}") # 2
print(f"pt_3d_tensor ndim: {pt_3d_tensor.dim()}") # 3

print("\n--- NumPy Number of Dimensions ---")
print(f"np_scalar ndim: {np_scalar.ndim}") # 0
print(f"np_vector ndim: {np_vector.ndim}") # 1
print(f"np_matrix ndim: {np_matrix.ndim}") # 2
print(f"np_3d_array ndim: {np_3d_array.ndim}") # 3

--- PyTorch Number of Dimensions ---
pt_scalar ndim: 0
pt_vector ndim: 1
pt_matrix ndim: 2
pt_3d_tensor ndim: 3

--- NumPy Number of Dimensions ---
np_scalar ndim: 0
np_vector ndim: 1
np_matrix ndim: 2
np_3d_array ndim: 3


#### Number of Elements (`.size` / `.numel()`)

In [7]:
print("--- PyTorch Number of Elements ---")
print(f"pt_scalar numel: {pt_scalar.numel()}") # 1
print(f"pt_vector numel: {pt_vector.numel()}") # 4
print(f"pt_matrix numel: {pt_matrix.numel()}") # 6
print(f"pt_3d_tensor numel: {pt_3d_tensor.numel()}") # 2*3*4 = 24

print("\n--- NumPy Number of Elements ---")
print(f"np_scalar size: {np_scalar.size}") # 1
print(f"np_vector size: {np_vector.size}") # 4
print(f"np_matrix size: {np_matrix.size}") # 6
print(f"np_3d_array size: {np_3d_array.size}") # 2*3*4 = 24

--- PyTorch Number of Elements ---
pt_scalar numel: 1
pt_vector numel: 4
pt_matrix numel: 6
pt_3d_tensor numel: 24

--- NumPy Number of Elements ---
np_scalar size: 1
np_vector size: 4
np_matrix size: 6
np_3d_array size: 24


#### Data Type (`.dtype`)

In [8]:
print(f"pt_vector dtype: {pt_vector.dtype}") # torch.int64
print(f"pt_3d_tensor dtype: {pt_3d_tensor.dtype}") # torch.float32
print(f"np_vector dtype: {np_vector.dtype}") # int64
print(f"np_3d_array dtype: {np_3d_array.dtype}") # float64

pt_vector dtype: torch.int64
pt_3d_tensor dtype: torch.float32
np_vector dtype: int64
np_3d_array dtype: float64


In [12]:
# --- PyTorch ---
x_pt = torch.arange(12) # Shape: [12]
print(f"Original x_pt: {x_pt}, shape: {x_pt.shape}")

# Reshape to 3x4
x_pt_reshaped = x_pt.reshape(3, 4)
print(f"Reshaped (3,4) x_pt:\n{x_pt_reshaped}, shape: {x_pt_reshaped.shape}")

# Using -1: PyTorch/NumPy can infer one dimension
x_pt_reshaped_infer = x_pt.reshape(2, -1) # Infers 6 for the second dimension
print(f"Reshaped (2,-1) x_pt:\n{x_pt_reshaped_infer}, shape: {x_pt_reshaped_infer.shape}")

# .view() example
# x_pt is contiguous, so view works
x_pt_view = x_pt.view(4, 3)
print(f"Viewed (4,3) x_pt:\n{x_pt_view}, shape: {x_pt_view.shape}")


Original x_pt: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), shape: torch.Size([12])
Reshaped (3,4) x_pt:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), shape: torch.Size([3, 4])
Reshaped (2,-1) x_pt:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), shape: torch.Size([2, 6])
Viewed (4,3) x_pt:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), shape: torch.Size([4, 3])


##### `.reshape()` or `.view()`
- `.view()` requires the tensor's underlying data to be **contiguous** in memory (new shapes but *without* changing the order of data in memory).
- `.reshape()`: A more flexible method.
    1. Tries to behave as `.view()`
    2. Create a copy of the data and re-arrange in memory if the data was not contiguous

1. `original_tensor` (3x4) is C-contiguous. Its elements are stored in memory like: `0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11`.
    - Strides `(4, 1)`: To get to the next row, skip 4 elements; to get to the next column, skip 1 element.

In [19]:
# 1. Create an original contiguous tensor
original_tensor = torch.arange(12).reshape(3, 4)
print(f"Original tensor: \n{original_tensor}")
print(f"Original tensor shape: \n{original_tensor.shape}")
print(f"Original tensor strides: \n{original_tensor.stride()}")
print(f"Is original tensor contiguous? {original_tensor.is_contiguous()}") # True
print(f"Original tensor data_ptr: {original_tensor.data_ptr()}") # Memory address

Original tensor: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Original tensor shape: 
torch.Size([3, 4])
Original tensor strides: 
(4, 1)
Is original tensor contiguous? True
Original tensor data_ptr: 445753088


In [29]:
# 2. Transpose it. This often makes the tensor non-contiguous for certain views.
transposed_tensor = original_tensor.transpose(0, 1) # Shape: [4, 3]
print(f"\nTransposed tensor:\n{transposed_tensor}")
print(f"Transposed tensor shape: {transposed_tensor.shape}")
# Strides change: (1, 4). This means to go to the next element in dim 0 (row),
# you jump 1 in memory. To go to next element in dim 1 (col), you jump 4 in memory.
print(f"Transposed tensor strides: {transposed_tensor.stride()}")
# It might still be "contiguous" in a general sense (e.g. Fortran-contiguous),
# but not necessarily C-contiguous in a way that allows all views.
print(f"Is transposed tensor C-contiguous? {transposed_tensor.is_contiguous()}") # This might be False!
print(f"Transposed tensor data_ptr: {transposed_tensor.data_ptr()}") # Same memory address as original


Transposed tensor:
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
Transposed tensor shape: torch.Size([4, 3])
Transposed tensor strides: (1, 4)
Is transposed tensor C-contiguous? False
Transposed tensor data_ptr: 445753088


In [30]:
# 3. Try to .view() the transposed tensor into a flat shape (e.g., 12 elements)
try:
    # Attempt to view it as a 1D tensor of 12 elements or a 2x6 tensor
    viewed_tensor = transposed_tensor.view(12)
    # viewed_tensor = transposed_tensor.view(2, 6) # This would also fail for the same reason
    print(f"\nViewed tensor (this might not be reached if error):\n{viewed_tensor}")
    print(f"Viewed tensor data_ptr: {viewed_tensor.data_ptr()}")
except RuntimeError as e:
    print(f"\nError using .view() on transposed_tensor: {e}")
    print("This error occurs because the transposed tensor's memory layout is not compatible with the target view.")

# 4. Now, try .reshape() on the same transposed tensor
reshaped_tensor = transposed_tensor.reshape(12)
# reshaped_tensor = transposed_tensor.reshape(2, 6) # This would also work
print(f"\nReshaped tensor:\n{reshaped_tensor}")
print(f"Reshaped tensor shape: {reshaped_tensor.shape}")
print(f"Is reshaped tensor contiguous? {reshaped_tensor.is_contiguous()}") # True, because reshape made a copy
print(f"Reshaped tensor data_ptr: {reshaped_tensor.data_ptr()}")
# Note: data_ptr for reshaped_tensor will likely be DIFFERENT from transposed_tensor
# if a copy was made. If reshape could make a view, it would be the same.

print(f"\nDid reshape share memory with transposed_tensor? {'Yes' if reshaped_tensor.data_ptr() == transposed_tensor.data_ptr() else 'No, a copy was made.'}")


Error using .view() on transposed_tensor: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
This error occurs because the transposed tensor's memory layout is not compatible with the target view.

Reshaped tensor:
tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])
Reshaped tensor shape: torch.Size([12])
Is reshaped tensor contiguous? True
Reshaped tensor data_ptr: 446261952

Did reshape share memory with transposed_tensor? No, a copy was made.


In [31]:
# Let's try to make a view that IS compatible with the transposed tensor's strides
# transposed_tensor has shape (4,3) and strides (1,4)
# A view to (4,3) should still work as it's the same shape/strides
try:
    compatible_view = transposed_tensor.view(4,3)
    print(f"\nCompatible view (4,3) on transposed_tensor works:\n{compatible_view}")
    print(f"Is compatible_view contiguous? {compatible_view.is_contiguous()} (same as transposed)")
    print(f"Compatible_view data_ptr: {compatible_view.data_ptr()} (same as transposed)")
except RuntimeError as e:
    print(f"\nError with compatible view: {e}") # Should not happen


Compatible view (4,3) on transposed_tensor works:
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
Is compatible_view contiguous? False (same as transposed)
Compatible_view data_ptr: 445753088 (same as transposed)
